apiVersion: apps/v1
kind: Deployment
metadata:
  name: se3200-frontend
  labels:
    app: se3200-app
    tier: frontend
spec:
  replicas: 2
  selector:
    matchLabels:
      app: se3200-app
      tier: frontend
  template:
    metadata:
      labels:
        app: se3200-app
        tier: frontend
    spec:
      containers:
        - name: frontend
          image: sscores/se3200-frontend:latest
          ports:
            - containerPort: 80
