apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: se3200-ingress
  annotations:
    kubernetes.io/ingress.class: nginx
spec:
  rules:
    - host:  k8s1
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: se3200-frontend
                port:
                  number: 80
          - path: /api
            pathType: Prefix
            backend:
              service:
                name: se3200-backend
                port:
                  number: 5000
